### ISSUE TITLE
extracting rules from json/yaml is going to break with newly proposed configuration.

### ISSUE THREAD

**Issue by greed2411** [Vernacular-ai/dialogy-template-simple-transformers#19]
presently `dialogy` users provide a `config.yaml` and it has a `rules` section straight out of the box.

like:
```yaml
rules:
  slots:
    block:
      product: product_kind
      actions: actions
      states: states
```

but in the future, we are nesting it under:

```yaml
postprocess:
  - plugin: "RuleBasedSlotFillerPlugin"
    params: 
      rules:
        slots:
          block:
            product: product_kind
            actions: actions
            states: states
```

so we need to update [slu/utils/config.py](https://github.com/Vernacular-ai/dialogy-template-simple-transformers/blob/f3a1ff820864af8b13602e59b0f80db18b2fe3e0/slu/slu/utils/config.py) to handle this situation. especially by fixing [this line 158](https://github.com/Vernacular-ai/dialogy-template-simple-transformers/blob/f3a1ff820864af8b13602e59b0f80db18b2fe3e0/slu/slu/utils/config.py#L158). without making breaking changes to existing dialogy-based projects.
